### ISSUE TITLE
jpeg to jpg

### ISSUE THREAD

**Issue by Sonyk91** [mwijnands/JpegMetadata#2]
https://github.com/mwijnands/JpegMetadata/blob/master/JpegMetadata/JpegMetadataAdapter.cs
if (frameMetadata == null)
{
    var frameMetadata = new BitmapMetadata("jpeg");   // replace by jpg
}

**Comment by mwijnands** [comment]
Hi Sonyk91,

On which version of Windows was this required?

**Comment by mwijnands** [comment]
Ah I see, in .NET 3.5 is was jpeg: https://msdn.microsoft.com/en-us/library/system.windows.media.imaging.bitmapmetadata.bitmapmetadata(v=vs.90).aspx

In .NET 4.0 and above it is jpg: https://msdn.microsoft.com/en-us/library/system.windows.media.imaging.bitmapmetadata.bitmapmetadata(v=vs.100).aspx

I'll see how I can fix this, or maybe I'll just make the library .NET 4.0+.
